apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNoExternalServices
metadata:
  name: no-external-services
  annotations:
    configmanagement.gke.io/cluster-selector: selector-env-dev
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["*"]
  parameters:
    internalCIDRs: 
      - "11.0.0.0/8"